// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project2_Sem3.Data;

#nullable disable

namespace Project2_Sem3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240327164812_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("Project2_Sem3.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Achievements")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Client")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .HasColumnType("TEXT");

                    b.Property<string>("EducationalQualification")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sex")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "G001",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-01.jpg",
                            Name = "Bun Laura",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G002",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-02.jpg",
                            Name = "Bun Hara",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G003",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-03.jpg",
                            Name = "Mab Jahgy",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G004",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-04.jpg",
                            Name = "kan BUug",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G005",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-05.jpg",
                            Name = "Hanh Jsi",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G006",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-06.jpg",
                            Name = "Ks Haby",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G007",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-07.jpg",
                            Name = "Kja Xag",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G008",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-08.jpg",
                            Name = "Rva Ham",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G009",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-09.jpg",
                            Name = "Ea Chu",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G010",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-10.jpg",
                            Name = "Bahu Fy",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G011",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-11.jpg",
                            Name = "Uab Bak",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G012",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-12.jpg",
                            Name = "Ta Ha",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G013",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-13.jpg",
                            Name = "Kab Banh",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G014",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-14.jpg",
                            Name = "Cag Hai",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G015",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-15.jpg",
                            Name = "Jauu Ban",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G016",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-16.jpg",
                            Name = "Baj Mabj",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G017",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-17.jpg",
                            Name = "Hani Bahy",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G018",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-18.jpg",
                            Name = "Lanu Trae",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G019",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-19.jpg",
                            Name = "Tayu Bau",
                            Role = "Developer",
                            Sex = "male"
                        },
                        new
                        {
                            Id = "G020",
                            Achievements = "Completed project X",
                            Address = "123 Main Street",
                            Client = "Client A",
                            ContactNumber = "1234567890",
                            Department = "Director",
                            EducationalQualification = "Bachelor's Degree",
                            EmployeeCode = "EMP001",
                            Grade = "A",
                            Image = "/images/team/team-20.jpg",
                            Name = "Caf Dar",
                            Role = "Developer",
                            Sex = "male"
                        });
                });

            modelBuilder.Entity("Project2_Sem3.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceImg")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Service", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "At [Company Name], we understand the paramount importance of safeguarding your assets, whether they be physical locations, data, or personnel. That's why we are proud to offer comprehensive security solutions tailored to meet your specific needs.\n\nOur team of highly trained security professionals is dedicated to providing top-tier protection for your business, ensuring peace of mind for you and your stakeholders. From on-site security personnel to advanced surveillance systems and access control measures, we employ the latest technologies and methodologies to mitigate risks and prevent unauthorized access.\n\nWith our proactive approach and unwavering commitment to excellence, you can trust us to safeguard your interests and uphold the highest standards of security at all times. Partner with us today and experience the difference that professional security services can make for your organization.",
                            Name = "Private Security",
                            ServiceImg = "/images/serviece/service-01.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Description = "At [Company Name], we understand the paramount importance of safeguarding your assets, whether they be physical locations, data, or personnel. That's why we are proud to offer comprehensive security solutions tailored to meet your specific needs.\n\nOur team of highly trained security professionals is dedicated to providing top-tier protection for your business, ensuring peace of mind for you and your stakeholders. From on-site security personnel to advanced surveillance systems and access control measures, we employ the latest technologies and methodologies to mitigate risks and prevent unauthorized access.\n\nWith our proactive approach and unwavering commitment to excellence, you can trust us to safeguard your interests and uphold the highest standards of security at all times. Partner with us today and experience the difference that professional security services can make for your organization.",
                            Name = "Transport Security",
                            ServiceImg = "/images/serviece/service-02.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Description = "At [Company Name], we understand the paramount importance of safeguarding your assets, whether they be physical locations, data, or personnel. That's why we are proud to offer comprehensive security solutions tailored to meet your specific needs.\n\nOur team of highly trained security professionals is dedicated to providing top-tier protection for your business, ensuring peace of mind for you and your stakeholders. From on-site security personnel to advanced surveillance systems and access control measures, we employ the latest technologies and methodologies to mitigate risks and prevent unauthorized access.\n\nWith our proactive approach and unwavering commitment to excellence, you can trust us to safeguard your interests and uphold the highest standards of security at all times. Partner with us today and experience the difference that professional security services can make for your organization.",
                            Name = "Home Security",
                            ServiceImg = "/images/serviece/service-03.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Description = "At [Company Name], we understand the paramount importance of safeguarding your assets, whether they be physical locations, data, or personnel. That's why we are proud to offer comprehensive security solutions tailored to meet your specific needs.\n\nOur team of highly trained security professionals is dedicated to providing top-tier protection for your business, ensuring peace of mind for you and your stakeholders. From on-site security personnel to advanced surveillance systems and access control measures, we employ the latest technologies and methodologies to mitigate risks and prevent unauthorized access.\n\nWith our proactive approach and unwavering commitment to excellence, you can trust us to safeguard your interests and uphold the highest standards of security at all times. Partner with us today and experience the difference that professional security services can make for your organization.",
                            Name = "Self Security",
                            ServiceImg = "/images/serviece/service-04.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Description = "At [Company Name], we understand the paramount importance of safeguarding your assets, whether they be physical locations, data, or personnel. That's why we are proud to offer comprehensive security solutions tailored to meet your specific needs.\n\nOur team of highly trained security professionals is dedicated to providing top-tier protection for your business, ensuring peace of mind for you and your stakeholders. From on-site security personnel to advanced surveillance systems and access control measures, we employ the latest technologies and methodologies to mitigate risks and prevent unauthorized access.\n\nWith our proactive approach and unwavering commitment to excellence, you can trust us to safeguard your interests and uphold the highest standards of security at all times. Partner with us today and experience the difference that professional security services can make for your organization.",
                            Name = "Offical Security",
                            ServiceImg = "/images/serviece/service-06.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
